// INJECT_COMPONENT_MARKER
// MAIN
export const MAIN_UPLOAD_READY = 'MAIN_UPLOAD_READY'
export const MAIN_INIT = 'MAIN_INIT'
export const MAIN_GET_TEXT_READY = 'MAIN_GET_TEXT_READY'

// ROOT
export const INIT = 'INIT'
export const THROTTLE_DELAY = 250
export const DATA_READY = 'DATA_READY'
export const TOGGLE_NAVIGATION = 'TOGGLE_NAVIGATION'
